CREATE TABLE estados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sigla VARCHAR(2),
  nome VARCHAR(50)
);

CREATE TABLE cidades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100),
  estado_id INT,
  FOREIGN KEY (estado_id) REFERENCES estados (id)
);

INSERT INTO estados (sigla, nome) VALUES 
('AC', 'Acre'),
('AL', 'Alagoas'),
('AP', 'Amapá'),
('AM', 'Amazonas'),
('BA', 'Bahia'),
('CE', 'Ceará'),
('DF', 'Distrito Federal'),
('ES', 'Espírito Santo'),
('GO', 'Goiás'),
('MA', 'Maranhão'),
('MT', 'Mato Grosso'),
('MS', 'Mato Grosso do Sul'),
('MG', 'Minas Gerais'),
('PA', 'Pará'),
('PB', 'Paraíba'),
('PR', 'Paraná'),
('PE', 'Pernambuco'),
('PI', 'Piauí'),
('RJ', 'Rio de Janeiro'),
('RN', 'Rio Grande do Norte'),
('RS', 'Rio Grande do Sul'),
('RO', 'Rondônia'),
('RR', 'Roraima'),
('SC', 'Santa Catarina'),
('SP', 'São Paulo'),
('SE', 'Sergipe'),
('TO', 'Tocantins');

INSERT INTO cidades (nome, estado_id) VALUES
('Rio Branco', 1),
('Cruzeiro do Sul', 1),
('Maceió', 2),
('Arapiraca', 2),
('Macapá', 3),
('Santana', 3),
('Manaus', 4),
('Parintins', 4),
('Salvador', 5),
('Feira de Santana', 5),
('Fortaleza', 6),
('Caucaia', 6),
('Brasília', 7),
('Taguatinga', 7),
('Vitória', 8),
('Cariacica', 8),
('Goiânia', 9),
('Aparecida de Goiânia', 9),
('São Luís', 10),
('Imperatriz', 10),
('Cuiabá', 11),
('Várzea Grande', 11),
('Campo Grande', 12),
('Dourados', 12),
('Belo Horizonte', 13),
('Contagem', 13),
('Belém', 14),
('Ananindeua', 14),
('João Pessoa', 15),
('Campina Grande', 15),
('Curitiba', 16),
('Londrina', 16),
('Recife', 17),
('Jaboatão dos Guararapes', 17),
('Teresina', 18),
('Parnaíba', 18),
('Rio de Janeiro', 19),
('São Gonçalo', 19),
('Natal', 20),
('Mossoró', 20),
('Porto Alegre', 21),
('Caxias do Sul', 21),
('Porto Velho', 22),
('Ji-Paraná', 22),
('Boa Vista', 23),
('Rorainópolis', 23),
('Florianópolis', 24),
('Joinville', 24),
('São Paulo', 25),
('Guarulhos', 25),
('Aracaju', 26),
('Nossa Senhora do Socorro', 26),
('Araguaína', 27),
('Palmas', 27);