CREATE TABLE abrigos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  telefone VARCHAR(20) NOT NULL,
  cidade_id INT NOT NULL,
  FOREIGN KEY (cidade_id) REFERENCES cidades (id)
);
