ALTER TABLE portes ADD UNIQUE (descricao);

ALTER TABLE estados
ADD UNIQUE (sigla),
ADD UNIQUE (nome),
MODIFY COLUMN sigla VARCHAR(2) NOT NULL,
MODIFY COLUMN nome VARCHAR(50) NOT NULL;

ALTER TABLE cidades 
MODIFY COLUMN nome VARCHAR(100) NOT NULL,
MODIFY COLUMN estado_id INT NOT NULL;